---
- name: Ensure containerd service folder exists
  file:
    path: /etc/systemd/system/containerd.service.d
    state: directory

- name: Override containerd service configuration
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/containerd.service.d/override.conf
  register: override_template

- name: Reload systemd daemon if template is changed
  systemd:
    daemon_reload: true
  when: override_template is changed
