---

- name: Determine Linux distribution
  debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }})"

- name: Gather {{ ansible_os_family }} OS family specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check prerequisites
  include_tasks: check_prerequisites.yml

- name: Install Docker Engine
  include_tasks: install_docker_engine.yml

- name: Post installation steps for Linux
  include_tasks: post_installation_steps_for_linux.yml

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present
  when: docker_install_compose
