---

- name: Manage Docker as a non-root user
  block:

  - name: Create the docker group
    group:
      name: docker
      state: present

  - name: Add users to the docker group
    user:
      name: "{{ item }}"
      groups: docker
      append: true
    loop: "{{ docker_users }}"

  when: docker_users is defined

- name: Configure Docker to start on boot
  service:
    name: docker
    enabled: true
    state: started
  when: docker_start_on_boot

- name: Ensure handlers are notified to avoid firewall conflicts
  meta: flush_handlers

- name: Install Docker SDK for Python
  pip:
    name: "{{ docker_pip_packages }}"
    state: present
